=pod

=encoding utf8

=head1 NAME

Sixteen Colors

=head1 SYNOPSIS

etc/sixteencolors_server.pl

=head1 DESCRIPTION

An ANSI/ASCII Art Archive

=head1 INSTALLATION

=head2 Setup Modules

        perl Makefile.PL ; make

=head2 Setup Database

        etc/deploy_schema.pl

=head2 Setup Artpacks

        etc/index_packs.pl 2000 /path/to/artpacks/2000/*.*

=head1 BUGS

	http://github.com/sixteencolors/sixteencolors/issues

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
